[package]
name = "wtiirn"
version = "0.1.0"
authors = ["Dorian Scheidt <dorian.scheidt@gmail.com>"]
edition = "2018"

[dependencies]
simple-server = "0.4.0"
log = "0.4"
env_logger = "0.6.1"
chrono = "0.4"
